### ISSUE TITLE
outsideClickClose keeps getting error. 

### ISSUE THREAD

**Issue by Dannyboy222** [shiv-chan/senpai-kohai#10]
there was problem with using `e.target` then I got solved with adding ` as Node` `(e.target as Node)` but the function does not really work at the moment. Prab and I have been trying to solve this problem.

**Comment by shiv-chan** [comment]
@Dannyboy222 @miyabitanimchi 

I tried to write the code and it worked okay.

1. Set `menu` class on the element(s) on where you don't want to close the menu overlay by clicking - in this case, `<header>` and the [menu overlay](https://github.com/shiv-chan/senpai-kohai/blob/f0a059f45d254359f1505782df23f7df77796d03/client/src/common/components/Header.tsx#L67-L82).
2. Created [`closeClickingOutsideMenu` function ](https://github.com/shiv-chan/senpai-kohai/blob/f0a059f45d254359f1505782df23f7df77796d03/client/src/common/components/Header.tsx#L45-L49). If the clicked element is outside the element(s) that has `menu` class, set `isOpen` state false.
3. Added a click event listener to the entire document which executes `closeClickingOutsideMenu` function. View [here](https://github.com/shiv-chan/senpai-kohai/blob/f0a059f45d254359f1505782df23f7df77796d03/client/src/common/components/Header.tsx#L51-L53).

Please check the header component file [here](https://github.com/shiv-chan/senpai-kohai/blob/feature-suggestion-header/client/src/common/components/Header.tsx#L45-L49).

**Comment by miyabitanimchi** [comment]
@Dannyboy222 @shiv-chan 
I deleted [the addEventListener()](https://github.com/shiv-chan/senpai-kohai/pull/15/files#diff-3794950e99d67d640efdc32ac2c0a0ae7729d8942962ac6cf5bd039d823ed5b7L45-L53) because it will unnecessarily be executed even when the header dropdown menu is closed.
For the solution, I added an [overlay](https://github.com/shiv-chan/senpai-kohai/pull/15/files#diff-3794950e99d67d640efdc32ac2c0a0ae7729d8942962ac6cf5bd039d823ed5b7R73-R84)  just under the menu

**Comment by miyabitanimchi** [comment]
@Dannyboy222 @shiv-chan 
I deleted [the addEventListener()](https://github.com/shiv-chan/senpai-kohai/pull/15/files#diff-3794950e99d67d640efdc32ac2c0a0ae7729d8942962ac6cf5bd039d823ed5b7L45-L53) because it will unnecessarily be executed even when the header dropdown menu is closed.
For the solution, I added an [overlay](https://github.com/shiv-chan/senpai-kohai/pull/15/files#diff-3794950e99d67d640efdc32ac2c0a0ae7729d8942962ac6cf5bd039d823ed5b7R73-R84) that covers whole body except the header and menu, and the dropdown menu and the overlay always move together. 
And with the overlay you can close the menu too.

#15 to see the code
